### ISSUE TITLE
Some questions about the substitute models for SCF

### ISSUE THREAD

**Issue by venus1215** [ThyrixYang/IDToolkit#1]
Dear Professor：
         I have used the GBDT checkpoints for SCF provided by you, but the results from the proxy model are quite different from the real calculated results. What is the reason for this?
         The following figure shows the specific configuration and results
![微信图片_20230612110511](https://github.com/ThyrixYang/IDToolkit/assets/58465245/56b0026a-3bd0-4490-9a79-aa06d2977f28)
![微信图片_20230612110516](https://github.com/ThyrixYang/IDToolkit/assets/58465245/2695ddf9-1833-4ec7-93cc-dc0b65cce299)
![微信图片_20230612110519](https://github.com/ThyrixYang/IDToolkit/assets/58465245/85e06e3f-118b-4451-b7bb-5c983126de4a)

**Comment by ThyrixYang** [comment]
Hi @venus1215 ,
Thanks for your interest in our benchmark! 

We have reproduced your results on this input. There are several reasons 

1. As we mentioned in our paper section 3.5 *Comparing to other scientific design
problems*. The surrogate models trained with machine learning methods may not be accurate evaluation functions. While machine learning models typically have high precision on the training and testing dataset generated from the same distribution, the precision drops significantly on the generated designs (or handcraft parameters given by you). We attribute this performance drop to the fact that the designed parameters are indeed out-of-distribution (OOD) samples, which breaks the generalization guarantee of the learning-based estimators. Thus, our physical simulator is necessary for an accurate evaluation of nanophotonic inverse design methods.
2. We propose the utilization of a surrogate model as an expedient approach for validating a design algorithm, while acknowledging the indispensability of the simulator for the ultimate evaluation.
3. We furnished a dataset generated through uniform sampling and the simulator, and the surrogate model was trained using this dataset. To enhance the accuracy of the surrogate model, one can augment the training dataset by incorporating new data and subsequently train a fresh model using the script provided in this repository. The pursuit of constructing a precise surrogate model constitutes the crux of the inverse design problem and remains an unresolved challenge.

For assessing the performance on the dataset or randomly generated parameters, you may refer to the code snippets provided below. The outcomes obtained should exhibit proximity to the mean squared error (MSE) reported in the Appendix.
```python
def scf():
    env = ColorFilterEnv()
    env_substitute = ColorFilterEnv(substitute_model_name='xgboost', ensemble=True)

    params = env.sample()
    print(params)
    env_substitute_pred = env_substitute.forward(params)
    env_pred = env.forward(params)
    print(env_substitute_pred)
    print(env_pred)
    print(np.mean((env_substitute_pred - env_pred)**2))
    
def scf_dataset():
    data_params, data_values = load_dataset("IDToolkit/datasets/color_filter")
    env = ColorFilterEnv()
    env_substitute = ColorFilterEnv(substitute_model_name='xgboost', ensemble=True)
    for i in range(10):
        idx = np.random.randint(len(data_params))
        p, v = data_params[idx], data_values[idx]
        print("param ", p)
        print("Dataset v ", v)
        env_substitute_pred = env_substitute.forward(p)
        print("substitute pred ", env_substitute_pred)
        env_pred = env.forward(p)
        print("env pred ", env_pred)
        print(np.mean((env_substitute_pred - env_pred)**2))
```

**Comment by ThyrixYang** [comment]
Please feel free to reopen this issue if you have any further questions regarding this problem. :)
