### ISSUE TITLE
Env Multi_Layer and function search 

### ISSUE THREAD

**Issue by fablos** [ThyrixYang/IDToolkit#2]
First I want to notice that the downloadable dataset Multi_Layer has a different size than the one indicated in the paper. That is $44400$ from the zip vs $60700$ claimed in the paper. Then, by running a simple experiment with your script `main.py` raises a `ValueError`. 

```bash
python experiments/main.py --env multi_layer --dataset_path datasets/multi_layer --eval_method real_target --method cvae --method_config experiments/configs/cvae
```
The issue is due to the `CombineSpace` which is not `all_numerical`. 

```bash
Traceback (most recent call last):
  File "IDToolkit/experiments/main.py", line 194, in <module>
    main(args)
  File "IDToolkit/experiments/main.py", line 105, in main
    pred_params = alg.search(num_samples=args.pred_num)
  File "IDToolkit/inverse_design_benchmark/algorithms/neural_opt.py", line 101, in search
    params = [self.env.parameter_space.from_numpy(p) for p in pred_params]
  File "IDToolkit/inverse_design_benchmark/algorithms/neural_opt.py", line 101, in <listcomp>
    params = [self.env.parameter_space.from_numpy(p) for p in pred_params]
  File "IDToolkit/inverse_design_benchmark/parameter_space/combine.py", line 72, in from_numpy
    raise ValueError("Only support converting numerical parameters from numpy")
ValueError: Only support converting numerical parameters from numpy
```

Are you aware of that ? Is there any workaround ? Thanks

**Comment by ShenJL** [comment]
Hi @fablos ,
Thanks for your interest in our benchmark!

As we have mentioned in the paper, deep learning methods only work for continuous variables currently, but does not well suit discrete variables. However, the MOTF cooler design problem involves both discrete (material type) and continuous (layer thickness) variables. When experimenting with multi_layer, we recommend using interactive optimizers. For more details, please refer to sample_script/inverse_design_iterative.sh.

**Comment by ThyrixYang** [comment]
Please feel free to re-open this issue if you have any further questions. :-)

**Comment by fablos** [comment]
Thank you so much for your response. I made some changes to your code and created a workaround specifically for MOTF.

Do you have any comments about the different sizes of the available dataset?

**Comment by ThyrixYang** [comment]
Hi @fablos, I sincerely apologize for any inconvenience caused by the inconsistency in the size of the dataset. During the preparation of the open-source data, we identified instances of data duplication, prompting us to remove duplicates. This did not impact our experimental conclusions. If a larger dataset is desired, one can utilize the data generation script provided in our codebase to generate additional data.

**Comment by fablos** [comment]
Yes, that's what I did. Thanks again for your response. By the way, I forgot to mention that I found your work very interesting. I will definitely incorporate your results into my next project.
